name: Publish to test PyPi.

on:
  push:
    branches: [ master ]

jobs:
  build-n-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install wheel
        run: python3 -m pip install wheel
      - name: Build a binary wheel and a source tarball
        run: python3 setup.py sdist bdist_wheel
      - name: Publish distribution 📦 to Test PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.TEST_PYPI_API_TOKEN }}
          repository-url: https://test.pypi.org/legacy/
          skip-existing: true
          verbose: true
